//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diplom_FastMedicine_
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin_Accounts
    {
        public decimal admin_id { get; set; }
        public string a_login { get; set; }
        public string a_password { get; set; }
        public string a_status { get; set; }
        public string a_type { get; set; }
    }
}
