//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diplom_FastMedicine_
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doc_Accounts
    {
        public decimal doctor_id { get; set; }
        public string doc_login { get; set; }
        public string doc_password { get; set; }
        public string doc_status { get; set; }
        public string doc_type { get; set; }
    
        public virtual Doctor Doctor { get; set; }
    }
}
