//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diplom_FastMedicine_
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doctor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Doctor()
        {
            this.Receptions = new HashSet<Reception>();
        }
    
        public decimal doctor_id { get; set; }
        public string doctor_name { get; set; }
        public string job_name { get; set; }
        public decimal room_number { get; set; }
        public string passport_series { get; set; }
        public string passport_number { get; set; }
        public int doc_experience { get; set; }
        public string phone_number { get; set; }
        public string doc_sex { get; set; }
        public string doc_birthdate { get; set; }
        public string doc_photo { get; set; }
        public string doc_card { get; set; }
        public decimal archive_number { get; set; }
        public string doc_status { get; set; }
        public string time_working { get; set; }
    
        public virtual Doc_Accounts Doc_Accounts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reception> Receptions { get; set; }
        public virtual Region Region { get; set; }
    }
}
