//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diplom_FastMedicine_
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MedicineContext : DbContext
    {
        public MedicineContext()
            : base("name=MedicineContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin_Accounts> Admin_Accounts { get; set; }
        public virtual DbSet<Agreement> Agreements { get; set; }
        public virtual DbSet<AnMorbi> AnMorbis { get; set; }
        public virtual DbSet<AnVitae> AnVitaes { get; set; }
        public virtual DbSet<Attendance> Attendances { get; set; }
        public virtual DbSet<Communication> Communications { get; set; }
        public virtual DbSet<Complaint> Complaints { get; set; }
        public virtual DbSet<Current_Status> Current_Status { get; set; }
        public virtual DbSet<Diagnosi> Diagnosis { get; set; }
        public virtual DbSet<Disease> Diseases { get; set; }
        public virtual DbSet<Doc_Accounts> Doc_Accounts { get; set; }
        public virtual DbSet<Doctor> Doctors { get; set; }
        public virtual DbSet<Identifier> Identifiers { get; set; }
        public virtual DbSet<Inspection> Inspections { get; set; }
        public virtual DbSet<Location> Locations { get; set; }
        public virtual DbSet<Medication> Medications { get; set; }
        public virtual DbSet<Passport> Passports { get; set; }
        public virtual DbSet<Patient> Patients { get; set; }
        public virtual DbSet<Patients_Money> Patients_Money { get; set; }
        public virtual DbSet<Preparation> Preparations { get; set; }
        public virtual DbSet<Reception> Receptions { get; set; }
        public virtual DbSet<Region> Regions { get; set; }
        public virtual DbSet<Research> Researches { get; set; }
        public virtual DbSet<Service> Services { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
