//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diplom_FastMedicine_
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Patient()
        {
            this.Receptions = new HashSet<Reception>();
        }
    
        public decimal patient_id { get; set; }
        public string patient_name { get; set; }
        public string birth_date { get; set; }
        public string photo_path { get; set; }
    
        public virtual Agreement Agreement { get; set; }
        public virtual Communication Communication { get; set; }
        public virtual Identifier Identifier { get; set; }
        public virtual Location Location { get; set; }
        public virtual Passport Passport { get; set; }
        public virtual Patients_Money Patients_Money { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reception> Receptions { get; set; }
    }
}
